### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'refactor_dir'

### ISSUE THREAD

**Issue by gerrymanoim** [isidentical/refactor#20]
Apologies if I've misunderstood how to use `refactor`. I was trying to run it with 

```
refactor -d test_refactor.py test.py
```

Where `test_refactor.py` is a file with my `Rule` and `test.py` is some source. I get an `AttributeError` at https://github.com/isidentical/refactor/blob/master/refactor/__main__.py#L45. Debugging, I think this should be `refactor_file = options.refactor_file`?

```
-> refactor_file = options.refactor_dir
(Pdb) options
Namespace(src=[PosixPath('test.py')], refactor_file=PosixPath('test_refactor.py'), dont_apply=True)
```

Python 3.9 / refactor 0.4.1.

**Comment by isidentical** [comment]
That is correct, thanks for catching it! I wonder why this has not been previously caught by the local pre-commit hook. Would you like to submit a PR to fix this / add a formal test?
