### ISSUE TITLE
Asterisk symbol not allowed in function args

### ISSUE THREAD

**Issue by feluelle** [isidentical/refactor#33]
When running refactor over the following code:
```python
    def __init__(self, *, foo):
        self.foo = foo
```

I get:
```
AttributeError: 'NoneType' object has no attribute '_fields'
```

**Comment by isidentical** [comment]
Can you share the Rule for this?

**Comment by feluelle** [comment]
Yes, sorry.

[This](https://github.com/feluelle/airflint/blob/main/airflint/rules/use_function_level_imports.py) is the rule. And [this](https://github.com/apache/airflow/blob/main/airflow/example_dags/example_dag_decorator.py) is the file I am trying to "refactor".

**Comment by hakancelikdev** [comment]
@feluelle Could you try adding `assert node.decorator_list` below line 20?

**Comment by hakancelikdev** [comment]
Hey, @isidentical I found the bug, I'll open a PR.
